---
title: "grand_function"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

PACKAGES AND FUNCTIONS
```{r}
pacman::p_load(tidyverse, readr, glmnet, data.table, broom, forcats, e1071, cvms)
source("functions/partition_function.R")
source("functions/Normalize_function.R")
source("functions/cv_functions.R")
source("functions/feature_selection.R")
source("functions/clean_column_function.R")
source("functions/correct_id.R")
source("functions/combine_dfs.R")
```

Loading data
```{r}
compare_dk <- read_csv("compare_dk.csv")
compare_us <- read_csv("compare_us.csv")
egemaps_dk <- read_csv("egemaps_dk.csv")
egemaps_us <- read_csv("egemaps_us.csv")
gemaps_dk  <- read_csv("gemaps_dk.csv") 
gemaps_us  <- read_csv("gemaps_us.csv")
demodata   <- read_csv("DemoData.csv")
```

The grand function to run
```{r}
grand_function <- function(feature_dataframe, 
                           other_dataframe,
                           demo_dataframe, 
                           lang, 
                           task,
                           featureset, 
                           n_lasso_folds = 5){
  set.seed(2021)
  ###Getting the correct dataframe###
  features <- feature_dataframe %>%  select(-name)

  ###Cleaning the data###
  
  #ID
  if (lang == "dk"){
    demo <- demo_dataframe %>% filter(language == "dk")
    features <- features %>% 
  mutate(ID = as.character(str_extract(ID, "[0-9]*")))
    
  demo <- demo %>% subset(ID != "103"& ID != "104"& ID !="105"& ID !="111"& ID !="114")
  }
  if (lang == "us"){
    demo <- demo_dataframe %>% filter(language == "us")
    features <- features %>% 
  mutate(
   ID = as.character(ID),  #Making ID character
   ID_letter = str_extract(ID, "[A-Z]+"), #extracting letters from ID name
   ID_number = str_extract(ID, "[0-9]*"))  #extracting numbers from ID name
   
  features$ID_letter <- ifelse(is.na(features$ID_letter), "", features$ID_letter)
   
  features <- features %>% 
    unite(ID, ID_letter:ID_number, sep = "") 
  }
  
  
  ###partitioning###
  if (lang == "dk"){
    partitions <- partition_dk(features = features, 
                               demo = demo)
  }
  if (lang == "us"){
    partitions <- partition_us(features = features,
                               demo = demo)
  }
   
  train <- partitions[[2]]
  train$ID <- as.character(train$ID)
  hold_out <- partitions[[1]]
  hold_out$ID <- as.character(hold_out$ID)

  #normalizing - scale_function takes min and max of all columns in train and subtracts min from all   values in each columns and divides by max value to get the empirically scaled columns
  train_scaled <- as.data.frame(
    scale_function(train, datatype = "train"))

  hold_out_scaled <- as.data.frame(
  scale_function(train, 
                 hold_out, 
                 datatype = "test"))
  
  other_dataframe <- other_dataframe %>% select(-name)
  if (lang != "dk"){
    other_dataframe <- other_dataframe %>% 
  mutate(ID = as.character(str_extract(ID, "[0-9]*")))
    
  demo <- demo %>% subset(ID != "103"& ID != "104"& ID !="105"& ID !="111"& ID !="114")
  }
    if (lang != "us"){
    other_dataframe <- other_dataframe %>% 
  mutate(
   ID = as.character(ID),  #Making ID character
   ID_letter = str_extract(ID, "[A-Z]+"), #extracting letters from ID name
   ID_number = str_extract(ID, "[0-9]*")  #extracting numbers from ID name
  )
  other_dataframe$ID_letter <- ifelse(is.na(other_dataframe$ID_letter), "", 
                                      other_dataframe$ID_letter)
  other_dataframe <- other_dataframe %>% 
    unite(ID, ID_letter:ID_number, sep = "") 
  }
  other_dataframe$ID <- as.character(other_dataframe$ID)
  other_dataframe$trial <- as.character(other_dataframe$trial)
  train$trial <- as.character(train$trial)
  
  hold_out_other_scaled <- as.data.frame(
  scale_function(train, 
                 other_dataframe, 
                 datatype = "test"))

  
  ###Combining demo and feature-set values###
  train_scaled <- combined_data(data = train_scaled, demo = demo)
  hold_out_scaled <- combined_data(data = hold_out_scaled, demo = demo)
  hold_out_other_scaled <- combined_data(data = hold_out_other_scaled, demo = demo)

  ###Removing column w/ zero variation and no factor variation###
  #badcolumns <- clean_cols(df = train_scaled)
  #print(badcolumns)
  #train_scaled <- train_scaled[ ,!(colnames(train_scaled) %in% c(badcolumns))] 
  
  ###Saving other_dataframe after scaling 
  write.csv(hold_out_other_scaled, 
            paste(paste(featureset, "not", lang, task, sep = "_"), "csv", sep = "."))
  
  train_task <- train_scaled %>% filter(condition == task)
  other_task <- train_scaled %>% filter(condition != task)
  write.csv(other_task, 
            paste(paste(featureset, lang, "not", task, sep = "_"), "csv", sep = "."))
  
  ###Lasso looping ###
  elastic(train_data = train_task,
                 folds = n_lasso_folds,
                 id_col = "ID",
                 featureset = featureset,
                 language = lang,
                 hold_set = hold_out_scaled,
                 task = task,
                 demo_set = demo)
  
}
```

###Run on combinations

dk, gemaps, stories
```{r}
grand_function(feature_dataframe = gemaps_dk, 
               other_dataframe = gemaps_us, 
               demo_dataframe = demodata, 
               lang = "dk", 
               task = "stories", 
               featureset = "gemaps")
```

dk, gemaps, triangles
```{r}
grand_function(feature_dataframe = gemaps_dk, 
               other_dataframe = gemaps_us, 
               demo_dataframe = demodata, 
               lang = "dk", 
               task = "triangles", 
               featureset = "gemaps")
```


dk, egemaps, stories 
```{r}
grand_function(feature_dataframe = egemaps_dk, 
               other_dataframe = egemaps_us, 
               demo_dataframe = demodata, 
               lang = "dk", 
               task = "stories", 
               featureset = "egemaps")
```

dk, egemaps, triangles
```{r}
grand_function(feature_dataframe = egemaps_dk, 
               other_dataframe = egemaps_us, 
               demo_dataframe = demodata, 
               lang = "dk", 
               task = "triangles", 
               featureset = "egemaps")
```

dk, compare, stories 
```{r}
grand_function(feature_dataframe = compare_dk, 
               other_dataframe = compare_us, 
               demo_dataframe = demodata, 
               lang = "dk", 
               task = "stories", 
               featureset = "compare")
```

dk, compare, triangles 
```{r}
grand_function(feature_dataframe = compare_dk, 
               other_dataframe = compare_us, 
               demo_dataframe = demodata, 
               lang = "dk", 
               task = "triangles", 
               featureset = "egemaps")
```

us, gemaps, stories
```{r}
grand_function(feature_dataframe = gemaps_us, 
               other_dataframe = gemaps_dk, 
               demo_dataframe = demodata, 
               lang = "us", 
               task = "stories", 
               featureset = "gemaps")
```

us, egemaps, stories
```{r}
grand_function(feature_dataframe = egemaps_us, 
               other_dataframe = egemaps_dk, 
               demo_dataframe = demodata, 
               lang = "us", 
               task = "stories", 
               featureset = "egemaps")
```

us, compare, stories 
```{r}
grand_function(feature_dataframe = compare_us, 
               other_dataframe = compare_dk, 
               demo_dataframe = demodata, 
               lang = "us",
               task = "stories", 
               featureset = "compare")
```

```{r}
source("functions/feature_selection.R")
```



